<<<<<<< HEAD

=======
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: devops-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/ChimataSrivalli/terraform-cicd-project.git
    targetRevision: main
    path: kubernetes

  destination:
    server: https://kubernetes.default.svc
    namespace: devops

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
>>>>>>> e1c0962 (change)
